---
title: "Codebook - Getting and Cleaning Data Course Project"
author: "J2"
date: "February 24, 2016"
output: html_document
---

#Overview
Human Activity Recognition database comprises the recordings of 30 subjects performing activities of daily living (ADL) while carrying a waist-mounted smartphone with embedded inertial sensors.  The experiments were carried out with a group of 30 volunteers, each person performed six activities (WALKING, WALKING UPSTAIRS, WALKING DOWNSTAIRS, SITTING, STANDING, LAYING), while wearing a smartphone (Samsung Galaxy S II) on the waist.  Using its embedded accelerometer and gyroscope, the researchers captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz.  The obtained dataset was randomly partitioned into two sets, where 70% (7352 observations) of the volunteers were selected for generating the training data and 30% (2947 observations) selected for the test data.    From this data two files were created: the first of which, run analysis.txt, contains measurements for which the means and standard deviations where estimated; the second, run analysis summary.txt contains the means of each of the variables in run_analysis.txt.

#File Structure - Input Files
The dataset for this project was downloaded from https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip.  A full description of the dataset was obtained from http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones.  The files used for this project are as follows.

**activity_labels.txt** - this file contains 2 variables (a number and an activity description) and 6 observations  -  one for each of the 6 following six activities as follows:

1.  WALKING
2.  WALKING_UPSTAIRS
3.  WALKING_DOWNSTAIRS
4.  SITTING
5.  STANDING
6.  LAYING

**features.txt** - a 561-feature vector with time and frequency domain variables.   The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. 

Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz.  

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag).  

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals).  These signals were used to estimate variables of the feature vector for each pattern:  '-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.
*	tBodyAcc-XYZ
*	tGravityAcc-XYZ
*	tBodyAccJerk-XYZ
*	tBodyGyro-XYZ
*	tBodyGyroJerk-XYZ
*	tBodyAccMag
*	tGravityAccMag
*	tBodyAccJerkMag
*	tBodyGyroMag
*	tBodyGyroJerkMag
*	fBodyAcc-XYZ
*	fBodyAccJerk-XYZ
*	fBodyGyro-XYZ
*	fBodyAccMag
*	fBodyAccJerkMag
*	fBodyGyroMag
*	fBodyGyroJerkMag

The set of variables that were estimated from these signals are: 
*	mean(): Mean value
*	std(): Standard deviation
*	mad(): Median absolute deviation 
*	max(): Largest value in array
*	min(): Smallest value in array
*	sma(): Signal magnitude area
*	energy(): Energy measure. Sum of the squares divided by the number of values. 
*	iqr(): Interquartile range 
*	entropy(): Signal entropy
*	arCoeff(): Autorregresion coefficients with Burg order equal to 4
*	correlation(): correlation coefficient between two signals
*	maxInds(): index of the frequency component with largest magnitude
*	meanFreq(): Weighted average of the frequency components to obtain a mean frequency
*	skewness(): skewness of the frequency domain signal 
*	kurtosis(): kurtosis of the frequency domain signal 
*	bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
*	angle(): Angle between to vectors.

Additional vectors obtained by averaging the signals in a signal window sample. These are used on the angle() variable:
*	gravityMean
*	tBodyAccMean
*	tBodyAccJerkMean
*	tBodyGyroMean
*	tBodyGyroJerkMean

**Test Files** - each of the following three files containing 2947 observations.
*	subject_test.txt - this file contains a vector indicating the test subject for each of the 2947 observations
*	X_test.txt - contains 2947 observations of the 561 features described above.
*	y_test.txt - contains a number 1:6, for each of the 2947 observations, indicating the activity that was performed by the subject.

**Train Files** - three files in the same structure as that of the test files.  The training file contains 7352 observations.

#File Structure - Output Files 
The output datasets, analysis.txt and analysis_summary.txt,  conform to the standards for tidy data, specifically that:

1.	Each variable measured should be in one column
2.	Each different observation of that variable should be in a different row
3.	There should be one table for each "kind" of variable
4.	Multiple tables should include a column in them that allows them to be linked.

There are two output files, and they are as follows:
**run_analysis.txt** - this file contains 10,299 observations of the following 68 variables
*	subject - the number, 1 thru 30, indicating the subject observed

*	activity-label - one of the following activities observed:
  + WALKING
  +	WALKING_UPSTAIRS
  +	WALKING_DOWNSTAIRS
  +	SITTING
  +	STANDING
  +	LAYING

*measurements  - of the 561 features, 66 features were selected which represented the mean and standard deviations for each measurement.  Note: '-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.  Note, that the variable names have been changed to be more descriptive.
+	time-body-accelerometer-mean-x,y,z
+	time-body-accelerometer-standard-deviation-x,y,z
+	time-gravity-accelerometer-mean-x,y,z
+	time-gravity-accelerometer-standard-deviation-x,y,z
+	time-body-accelerometer-jerk-mean-x,y,z
+	time-body-accelerometer-jerk-standard-deviation-x,y,z
+	time-body-gyroscope-mean-x,y,z
+	time-body-gyroscope-standard-deviation-x,y,z
+	time-body-gyroscope-jerk-mean-x,y,z
+	time-body-gyroscope-jerk-standard-deviation-x,y,z
+	time-body-accelerometer-mag-mean
+	time-body-accelerometer-mag-standard-deviation
+	time-gravity-accelerometer-mag-mean
+	time-gravity-accelerometer-mag-standard-deviation
+	time-body-accelerometer-jerkmag-mean
+	time-body-accelerometer-jerkmag-standard-deviation
+	time-body-gyroscope-mag-mean
+	time-body-gyroscope-mag-standard-deviation
+	time-body-gyroscope-jerkmag-mean
+	time-body-gyroscope-jerkmag-standard-deviation
+	frequency-body-accelerometer-mean-x,y,z
+	frequency-body-accelerometer-standard-deviation-x,y,z
+	frequency-body-accelerometer-jerk-mean-x,y,z
+	frequency-body-accelerometer-jerk-standard-deviation-x,y,z
+	frequency-body-gyroscope-mean-x,y,z
+	frequency-body-gyroscope-standard-deviation-x,y,z
+	frequency-body-accelerometer-mag-mean
+	frequency-body-accelerometer-mag-standard-deviation
+	frequency-body-body-accelerometer-jerkmag-mean
+	frequency-body-body-accelerometer-jerkmag-standard-deviation
+	frequency-body-body-gyroscope-mag-mean
+	frequency-body-body-gyroscope-mag-standard-deviation
+	frequency-body-body-gyroscope-jerkmag-mean
+	frequency-body-body-gyroscope-jerkmag-standard-deviation
